CREATE TABLE STUDENTS(
ID NUMBER(5) PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
STANDARD NUMBER(5),
ADDRESS VARCHAR2(50));
commit;
INSERT into STUDENTS (ID, NAME, STANDARD, ADDRESS) values(1,'Sajal',5, 'PUNE');
INSERT into STUDENTS (ID, NAME, STANDARD, ADDRESS) values(2,'Kajal',5, 'Chicago');
INSERT into STUDENTS (ID, NAME, STANDARD, ADDRESS) values(3,'Lokesh',6, 'Delhi');
INSERT into STUDENTS (ID, NAME, STANDARD, ADDRESS) values(4,'Sukesh',7, 'Noida');
commit;